packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - bufferutil
  - esbuild
  - msw
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
